README.md

Signed-off-by: Derek McQuay <derekmcquay@gmail.com>

add beta warning

---

README.md
add-ons/dashboard/kubernetes-dashboard.yaml

Adds instructions to install the Kubernetes Dashboard

Adds Dashboard add on

---

examples/os-detector/os-detector.md

Updating the os-detector readme to use the latest Cassandra package.

docs: Updating the os-detector readme

---

README.md
docs/azure.md

Adding details for Azure Customers.

docs: Adding details for Azure

---

Makefile

[fix] Makefile GCE setup

---

README.md
docs/existing_cluster.md

@spahl please review when the release is cut.

docs: point to release 0.2.2-1.7.7-beta

---

Makefile
README.md
resources/aws.template.mk
resources/azure.template.mk
resources/gce.template.mk

- Add azure template
- Move vm templates out of the Makefile

Makefile: add support for azure deployments

---

Dockerfile
Makefile
README.md
docs/aws.md
docs/existing_cluster.md

@spahl please review and then merge, pending the 0.3.0-1.7.10-beta release.

misc: upgrade beta-kubernetes to 0.3.0-1.7.10-beta.

---

resources/desired_cluster_profile.gcp

depends on PR https://github.com/dcos/terraform-dcos/pull/27

keep gcp variable names in sync with upstream TF

---

.gitignore
Makefile
README.md

blocked by https://github.com/dcos/terraform-dcos/pull/29

use master LB for cluster access

---

Makefile
README.md

This adds validation to required binaries, informing user if prereqs fail.
Also adds a one target cluster destroy (`make destroy`).

Makefile tweaks

---

README.md

Signed-off-by: Rimas Mocevicius <rmocius@gmail.com>

Improve readme: how to better check k8s install progress

---

Makefile
README.md

Even though docs are (once again!) not yet pushed, the new release is out!

dcos-kubernetes to 0.6.1-1.9.3-beta

---

Makefile
README.md
docs/aws.md
docs/azure.md
docs/existing_cluster.md
resources/desired_cluster_profile.aws
resources/desired_cluster_profile.azure
resources/desired_cluster_profile.gcp

Our first generally available release is out!

bump dcos-kubernetes to 1.0.0-1.9.3

---

Makefile

always write master ip to the files

fix terraform output values for master ip

---

Makefile
README.md
docs/aws.md
docs/azure.md
docs/cncf_conformance.md
docs/existing_cluster.md
resources/desired_cluster_profile.aws
resources/desired_cluster_profile.azure
resources/desired_cluster_profile.gcp
resources/options-ha.json

Bump dc/os to v1.11.1, add k8s HA docs, update makefile

Upgrade dcos v1 11 1

---

README.md
docs/cncf_conformance.md

with the changes framework version `1.1.1-1.10.4` brought in

update conformance and main readme docs

---

Makefile
README.md
docs/aws.md
docs/azure.md
docs/cncf_conformance.md
docs/existing_cluster.md
docs/exposing_kubernetes_api.md
resources/desired_cluster_profile.aws
resources/desired_cluster_profile.azure
resources/desired_cluster_profile.gcp

- bump version to kubernetes package to `1.2.2-1.10.7`
- bump DC/OS to `1.11.5`
[https://docs.mesosphere.com/service-docs/kubernetes/1.2.2-1.10.7](https://docs.mesosphere.com/service-docs/kubernetes/1.2.2-1.10.7)
[https://docs.mesosphere.com/services/kubernetes/1.2.2-1.10.7/release-notes/](https://docs.mesosphere.com/services/kubernetes/1.2.2-1.10.7/release-notes/)

bump kubernetes package to 1.2.2-1.10.7

---

Makefile
README.md
docs/aws.md
docs/azure.md
docs/cncf_conformance.md
docs/existing_cluster.md
docs/exposing_kubernetes_api.md
resources/desired_cluster_profile.aws
resources/desired_cluster_profile.azure
resources/desired_cluster_profile.gcp
resources/kubeapi-proxy.json
resources/options-ha.json
resources/options.json.aws
resources/options.json.azure
resources/options.json.gcp

Changes supporting newest versions of DCOS and DCOS-Kubernetes.
Notable items changed:
- Makefile 
- Readme

DC/OS 1.12 + Kubernetes 1.12

---

Makefile
README.md
docs/cncf_conformance.md
docs/existing_cluster.md
docs/exposing_kubernetes_api.md

Conformance results will be shared ASAP.
This PR should not be merged until package release is complete.

package: update to 2.3.0-1.14.1
